apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tensor-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tensor-app
  template:
    metadata:
      labels:
        app: tensor-app
    spec:
      containers:
      - name: my-tensor-app
        image: 343091671287.dkr.ecr.us-east-2.amazonaws.com/tensor-docker
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: tensor-app-svc
spec:
  selector:
    app: tensor-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer